DEBUG = true # booleanos geralmente são em minúsculas (true/false) no TOML, mas "True" pode funcionar dependendo do parser
CSV_PATH = "./.files/dataset/dados_ficticios.csv"
CSV_PATH_DIR = "./.files/dataset/"
VECTOR_PATH = "./.files/context-vector"
RULES_PATH = "./.files/rules/regras.txt"
QUESTION1 = "./.development/questions/q1.txt"
QUESTION2 = "./.development/questions/q2.txt"
QUESTION3 = "./.development/questions/q3.txt"
QUESTION4 = "./.development/questions/q4.txt"
GRAFICO_PATH = "./.files/.graph/grafico.html"
GOOGLE_API_KEY = ""
GEMINI_API_KEY = ""
NEW_DATASET_PATH = "./.files/.new-dataset"
MISTRAL_API_KEY = ""
MODEL_PROVIDER = "mistral"
MISTRAL_BASE_URL = ""
MAX_ITERATIONS = 100
ARCHIVE_NAME = "dataset.csv"
OPENAI_API_KEY = ""
